routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/get-city-register/{province}', 'Auth\RegisterController@get_city');
Route::get('/get-notification', 'NotificationController@notification');
Route::get('/get-notification-dashboard', 'NotificationController@notification_dashboard');
Route::get('/update-notification', 'NotificationController@fetch');
Route::get('/kontak', function(){
  return view('buyer.kontak');
});

Route::middleware(['isPembeli','verified'])->group(function () {

    Route::get('/checkout', 'CheckoutController@fill_form')->name('checkout');
    Route::get('/get-city/{province}', 'CheckoutController@get_city');
    Route::post('/get-price', 'CheckoutController@get_expedition');
    Route::post('/check-voucher', 'CheckoutController@check_voucher');
    Route::post('/proses-checkout', 'CheckoutController@proses_checkout');

    Route::resource('cart', 'CartController')->only([
        'index', 'store', 'destroy', 'update'
    ]);

    Route::get('/transaksi', 'TransaksiBuyerController@index');
    Route::post('/transaksi/terima', 'TransaksiBuyerController@terima');
    Route::post('/transaksi/cancel', 'TransaksiBuyerController@cancel');

    Route::get('/bayar/{code}', 'PembayaranController@index');
    Route::post('/upload-pembayaran', 'PembayaranController@upload_pembayaran');
    Route::post('/update-pembayaran', 'PembayaranController@upload_pembayaran');
    Route::get('/verifikasi/{code}', 'VerifikasiBuyerController@index');

    Route::post('/input-review', 'ProductController@review')->middleware('auth');

    Route::post('/proses-wishlist', 'WishlistController@proses_wishlist');
    Route::get('/wishlist', 'WishlistController@index');

});

Route::get('/produk', 'ProductController@index');
Route::post('/search', 'ProductController@search');

Route::get('/toko/{id}', 'StoreController@index');
Route::post('/hubungi-toko', 'ChatController@hubungi_toko');

Route::get('/detail-produk/{id}', 'ProductController@detail')->name('detail-produk');
Route::get('/get-stock-status/{id}/{size}', 'ProductController@get_stock');


Auth::routes();
Auth::routes(['verify' => true]); //for verify email

Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile', 'ProfileController@index');
Route::post('/profile/edit', 'ProfileController@edit');
Route::post('/profile/ubah-password', 'ProfileController@password');
Route::post('/profile/avatar', 'ProfileController@avatar');

Route::middleware('isSuperAdmin')->group(function () {
    Route::get('/manajemen-admin', 'ManajemenAdminController@index');
    Route::post('/manajemen-admin/tambah', 'ManajemenAdminController@tambah');
    Route::post('/manajemen-admin/delete', 'ManajemenAdminController@delete');
    Route::post('/manajemen-admin/edit', 'ManajemenAdminController@edit');
    Route::post('/manajemen-admin/get-edit-data', 'ManajemenAdminController@get');
    Route::get('/manajemen-admin/search', 'ManajemenAdminController@search')->name('admin.search');
});

Route::middleware('isAdmin')->group(function () {

    Route::get('/mengelola-voucher', 'VoucherController@index');
    Route::get('/mengelola-voucher/search', 'VoucherController@search')->name('voucher.search');
    Route::post('/mengelola-voucher/tambah', 'VoucherController@tambah');
    Route::post('/mengelola-voucher/delete', 'VoucherController@delete');
    Route::post('/mengelola-voucher/edit', 'VoucherController@edit');
    Route::post('/mengelola-voucher/get-edit-data', 'VoucherController@get');

    Route::get('/mengelola-kategori', 'KategoriController@index');
    Route::get('/mengelola-kategori/searcj', 'KategoriController@search')->name('kategori.search');
    Route::post('/mengelola-kategori/get-edit-data', 'KategoriController@get');
    Route::post('/mengelola-kategori/konfirmasi', 'KategoriController@konfirmasi');
    Route::post('/mengelola-kategori/tambah', 'KategoriController@tambah');
    Route::post('/mengelola-kategori/delete', 'KategoriController@delete');
    Route::post('/mengelola-kategori/edit', 'KategoriController@edit');

    Route::get('/mengelola-transaksi', 'TransaksiController@index')->name('transaction.index');
    Route::post('/mengelola-transaksi/verification', 'TransaksiController@verification')->name('transaction.verification');
    Route::post('/mengelola-transaksi/decline-proof', 'TransaksiController@decline_proof')->name('transaction.declineProof');
    Route::post('/mengelola-transaksi/cancel', 'TransaksiController@cancel')->name('transaction.cancel');
    Route::post('/mengelola-transaksi/kadaluarsa', 'TransaksiController@kadaluarsa')->name('transaction.kadaluarsa');

    Route::get('/mengelola-jicash', 'JiCashController@index');
    Route::post('/mengelola-jicash/verification', 'JiCashController@verification')->name('jicash.verification');
    Route::post('/mengelola-jicash/cancel', 'JiCashController@cancel')->name('jicash.cancel');
    Route::post('/mengelola-jicash/get-proof-jicash', 'JiCashController@get_proof_jicash')->name('jicash.proof');

    Route::get('/manajemen-penjual', 'ManajemenPenjualController@index');
    Route::get('/manajemen-penjual/saerch', 'ManajemenPenjualController@search')->name('penjual.search');
    Route::post('/manajemen-penjual/tambah', 'ManajemenPenjualController@tambah');
    Route::post('/manajemen-penjual/delete', 'ManajemenPenjualController@delete');
    Route::post('/manajemen-penjual/edit', 'ManajemenPenjualController@edit');
    Route::post('/manajemen-penjual/get-edit-data', 'ManajemenPenjualController@get');

    Route::get('/mengelola-toko', 'MengelolaTokoController@index');
    Route::get('/mengelola-toko/search', 'MengelolaTokoController@search')->name('toko.search');
    Route::post('/mengelola-toko/tambah', 'MengelolaTokoController@tambah');
    Route::post('/mengelola-toko/delete', 'MengelolaTokoController@delete');
    Route::post('/mengelola-toko/edit', 'MengelolaTokoController@edit');
    Route::post('/mengelola-toko/get-edit-data', 'MengelolaTokoController@get');

    Route::get('/mengelola-produk-admin', 'MengelolaProdukController@index');
    Route::get('/mengelola-produk-admin/search', 'MengelolaProdukController@search')->name('admin.produk.search');
    Route::post('/mengelola-produk-admin/tambah', 'MengelolaProdukController@tambah');
    Route::post('/mengelola-produk-admin/delete', 'MengelolaProdukController@delete');
    Route::post('/mengelola-produk-admin/edit', 'MengelolaProdukController@edit');
    Route::post('/mengelola-produk-admin/get-edit-data', 'MengelolaProdukController@get');
    Route::post('/mengelola-produk-admin/add-images', 'MengelolaProdukController@add_images');
    Route::post('/mengelola-produk-admin/delete-images', 'MengelolaProdukController@delete_images');
    Route::post('/mengelola-produk-admin/get-category-status', 'MengelolaProdukController@get_category_status')->name('category.status.admin');

});

Route::get('/chat', 'ChatController@index');
Route::post('/chat/send-message', 'ChatController@send_message');
Route::post('/chat/pilih-user', 'ChatController@pilih_user');

Route::middleware('isPenjual')->group(function () {

    Route::get('/mengelola-produk', 'MengelolaProdukController@index');
    Route::get('/mengelola-produk/search', 'MengelolaProdukController@search')->name('produk.search');
    Route::post('/mengelola-produk/tambah', 'MengelolaProdukController@tambah');
    Route::post('/mengelola-produk/delete', 'MengelolaProdukController@delete');
    Route::post('/mengelola-produk/edit', 'MengelolaProdukController@edit');
    Route::post('/mengelola-produk/get-edit-data', 'MengelolaProdukController@get');
    Route::post('/mengelola-produk/add-images', 'MengelolaProdukController@add_images')->name('add-images.penjual');
    Route::post('/mengelola-produk/delete-images', 'MengelolaProdukController@delete_images');
    Route::post('/mengelola-produk/get-category-status', 'MengelolaProdukController@get_category_status')->name('category.status');

    Route::get('/list-pesanan', 'TransaksiController@transaction_list')->name('transaction.list');
    Route::post('/mengelola-transaksi/verification-delivery', 'TransaksiController@verification_delivery')->name('transaction.verification_delivery');

    Route::get('/kelola-pendapatan', function () {
        return view('seller.pendapatan');
    });

});

Route::post('/mengelola-transaksi/get-detail-transaction', 'TransaksiController@get_detail_transaction')->name('transaction.detail');
Route::post('/mengelola-transaksi/get-proof-transaction', 'TransaksiController@get_proof_transaction')->name('transaction.proof');

resources/views/buyer/bayar.blade.php
@extends('layouts.client-layout')

@section('page', 'Checkout Produk')

@section('content')
<div class="container-fluid page">
  <div class="row">
    <div class="col-12 page-title">
      <h2>CHECKOUT</h2>
    </div>
  </div>
  <div class="checkout-container">
    @include('buyer.wizard')
    <hr>
    @foreach($transactions[0]->detail as $detail)
    @if($detail->shipping_status != 'OPTCC')
    <div class="row">
      <div class="col-12 text-left">
        <h3>{{ $detail->product->name }}
          {{--@isset($detail->status)
          <span class="badge badge-success">{{ $detail->status->value }}</span>
          @endisset--}}
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-lg-6">
        <p>Harga Produk</p>
      </div>
      <div class="col-xs-12 col-lg-6 text-right">
        <p class="font-weight-bold">Rp {{ number_format($detail->price, 2) }}</p>
      </div>
    </div>
    @endif
    @endforeach
    <hr>
    <div class="row">
      <div class="col-xs-12 col-lg-6">
        <p>Discount</p>
      </div>
      <div class="col-xs-12 col-lg-6 text-right">
        <p>Rp {{ number_format($transactions[0]->discount_amount, 2) }}</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-lg-6">
        <p>Biaya Jasa Ekspedisi</p>
      </div>
      <div class="col-xs-12 col-lg-6 text-right">
        <p>Rp {{ number_format($transactions[0]->shipping_charges, 2) }}</p>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-12 col-lg-9 text-right">
        <h2>Total Harga</h2>
      </div>
      <div class="col-xs-12 col-lg-3 text-right">
        <h3>Rp <span class="text-danger font-weight-bold">{{ number_format($transactions[0]->grand_total_amount, 2) }}</span></h3>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-12">
        <h2>Tata Cara Pembayaran</h2>
      </div>
      <div class="col-12">
        <p>Silahkan melakukan transaksi sesuai dengan waktu yang ditentukan,
          jika melebihi waktu maka akan dibatalkan oleh admin</p>
        </div>
      </div>
      <div class="row waktu text-center">
        <div class="col-12">
          <p>Sisa Waktu Bayar</p>
        </div>
        <div class="col-12 mb-5">
          <div id="timer" data-deadline="{{ $transactions[0]->payment->deadline_proof }}">
            <table class="text-center" align="center">
              <tr>
                <td><h2 class="text-danger" id="jam">00</h2></td>
                <td>:</td>
                <td><h2 class="text-danger" id="menit">00</h2></td>
                <td>:</td>
                <td><h2 class="text-danger" id="detik">00</h2></td>
              </tr>
              <tr>
                <td><p>Jam</p></td>
                <td></td>
                <td><p>Menit</p></td>
                <td></td>
                <td><p>Detik</p></td>
              </tr>
            </table>
          </div>
        </div>
        <div class="col-12">
          <p>No Rekening</p>
        </div>
        <div class="col-12">
          <h2>0086197911100</h2>
        </div>
        <div class="col-12">
          <p>a/n</p>
        </div>
        <div class="col-12 mb-5">
          <h2>Bumdes Pakis Sabilulungan</h2>
        </div>
        <div class="col-12 text-left">
          <form class="" action="{{ url('/upload-pembayaran') }}" method="post" enctype="multipart/form-data">
            @csrf
            <input type="text" name="code" value="{{ $transactions[0]->code }}" hidden>
            <p>Upload Bukti Bayar Disini : </p>
            <div class="input-group">
              <div class="custom-file">
                <input type="file" name="foto" class="custom-file-input" id="inputGroupFile04">
                <input type="text" name="transaction_code" value="{{ $transactions[0]->code }}" hidden>
                <label class="custom-file-label" for="inputGroupFile04">Pilih Bukti</label>
              </div>
              <div class="input-group-append">
                <button class="btn btn-success" type="submit">Upload</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  @endsection

  @push('script')
  <script type="text/javascript">
  var countDownDate = new Date($('#timer').data('deadline'));
  var x = setInterval(function() {

    var today = new Date().toLocaleString("en-US", {timeZone: "Asia/Jakarta"});
    var now = Date.parse(today);
    var distance = countDownDate - now;

    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    $('#jam').html(hours);
    $('#menit').html(minutes);
    $('#detik').html(seconds);

    //kalo deadline abis
    if (distance < 0) {
      clearInterval(x);
    }
  }, 1000);
  </script>
  <script type="text/javascript">
  $(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
  </script>
  @endpush

resources/views/buyer/cart.blade.php
@extends('layouts.client-layout')

@section('page', 'Cart Produk')

@section('content')
    <div class="container-fluid page">
        <div class="row">
            <div class="col-12 page-title">
                <h2>SHOPPING CART</h2>
            </div>
        </div>
        <div class="row container-cart">
            <div class="col-xs-12 col-lg-8">
                @isset($carts)
                    @foreach($carts as $cart)
                        <div class="section-cart">
                            <div class="row">
                                <div class="col-sm-11">
                                    <h2>{{ $cart->product->store->name }}</h2>
                                    <p>{{ $cart->product->store->address_1 }} <span class="fa fa-map-marker"></span></p>
                                </div>
                                <div class="col-sm-1 text-right">
                                    <input type="checkbox" value="{{ $cart->id }}" class="form-control cart-checkbox" checked>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-lg-2 text-center">
                                    @if (isset($cart->product->images[0]->image_name))
                                        <img src="{{ asset('assets/img/products') . $cart->product->images[0]->image_name }}" alt="Image 1" height="100px" width="100px">
                                    @else
                                        <img src="{{ asset('assets/img/products/product-1.jpg') }}" alt="Produk" height="100px" width="100px">
                                    @endisset
                                </div>
                                <div class="col-xs-12 col-lg-6">
                                    <h1>{{ $cart->product->name }}</h1>
                                    <p>
                                      @isset($cart->product->color)
                                      <span class="badge badge-light">{{ $cart->product->color }} </span>
                                      @endisset
                                      @isset($cart->cart_product_status)
                                      <span class="badge badge-success">{{ $cart->cart_product_status->value }}</span>
                                      @endisset
                                    </p>
                                    <input type="hidden" value="{{ $cart->product->price }}" class="product-price">
                                    <p><span>Rp {{ number_format($cart->product->price) }}</span>/pcs</p>
                                </div>
                                <div class="col-xs-12 col-lg-3">
                                    <div class="input-group">
                                        <span class="input-group-btn">
                                            <a class="btn btn-number" data-type="minus" data-field="quant{{ $loop->iteration }}">
                                                <span class="fa fa-minus"></span>
                                            </a>
                                        </span>
                                        <input type="text" name="quant{{ $loop->iteration }}" class="form-control text-center input-number"
                                               value="{{ $cart->quantity }}" min="1" max="{{ $cart->product->stock }}">
                                        <span class="input-group-btn">
                                            <a class="btn btn-number" data-type="plus" data-field="quant{{ $loop->iteration }}">
                                                <span class="fa fa-plus"></span>
                                            </a>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-lg-1">
                                    <form action="{{ route('cart.destroy', $cart->id) }}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-light"><span class="fa fa-trash"></span>
                                        </button>
                                    </form>
                                </div>
                                <div class="col-12">
                                    <input type="text" name="pesan" value=""
                                           placeholder="Masukan pesan kepada penjual (optional)" class="form-control pesan">
                                </div>
                            </div>
                        </div>
                    @endforeach
                @endisset;
            </div>
            <div class="col-xs-12 col-lg-4 cart-harga">
                <div class="section-harga">
                    <h2>Total Belanja</h2>
                    <form class="text-center" action="{{ url('cart/1') }}" method="POST" id="form-checkout">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="message" id="message" value="tes">
                        <input type="hidden" name="cart" value="">
                        <input type="hidden" name="quantity" value="">
                        <div class="harga">
                            <h1><b>Rp {{ number_format($shopping_charges) }},-</b></h1>
                        </div>
                        <button type="button" class="btn btn-success" name="button" id="btnCheckout"
                                onclick="check_cart()">Checkout
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')

    <script type="text/javascript">
        fillCart();

        $('.cart-checkbox, .input-number').change(function () {
            fillCart();
        });

        function fillCart() {
            var cart = [];
            var quantity = [];
            var message =[];
            var total = 0;
            $('.cart-checkbox:checked').each(function () {
                var qty = $(this).closest('.section-cart').find('.input-number').val();
                var price = $(this).closest('.section-cart').find('.product-price').val();
                var msg = $(this).closest('.section-cart').find('.pesan').val();

                cart.push(parseInt($(this).val()));
                quantity.push(parseInt(qty));
                message.push(msg);

                total += (qty * price);
            });

            $('.harga h1 b').html('Rp ' + total.toLocaleString() + ',-');

            $('input[name="cart"]').val(JSON.stringify(cart));
            $('input[name="quantity"]').val(JSON.stringify(quantity));
            $('input[name="message"]').val(JSON.stringify(message));
        }

        function check_cart() {
            fillCart();

            if ($('.cart-checkbox:checked').length < 1) {
                alert('Pilih Produk yang Ingin Anda Checkout!');
                return false;
            }

            $('#form-checkout').submit();
        }
    </script>

    <script type="text/javascript">
        $('.btn-number').click(function (e) {
            e.preventDefault();

            fieldName = $(this).attr('data-field');
            type = $(this).attr('data-type');
            var input = $("input[name='" + fieldName + "']");
            var currentVal = parseInt(input.val());
            if (!isNaN(currentVal)) {
                if (type == 'minus') {

                    if (currentVal > input.attr('min')) {
                        input.val(currentVal - 1).change();
                    }
                    if (parseInt(input.val()) == input.attr('min')) {
                        $(this).attr('disabled', true);
                    }

                } else if (type == 'plus') {

                    if (currentVal < input.attr('max')) {
                        input.val(currentVal + 1).change();
                    }
                    if (parseInt(input.val()) == input.attr('max')) {
                        $(this).attr('disabled', true);
                    }

                }
            } else {
                input.val(0);
            }
        });
        $('.input-number').focusin(function () {
            $(this).data('oldValue', $(this).val());
        });
        $('.input-number').change(function () {

            minValue = parseInt($(this).attr('min'));
            maxValue = parseInt($(this).attr('max'));
            valueCurrent = parseInt($(this).val());

            name = $(this).attr('name');
            if (valueCurrent >= minValue) {
                $(".btn-number[data-type='minus'][data-field='" + name + "']").removeAttr('disabled')
            } else {
                alert('Maaf, anda melebihi minimum pembelian');
                $(this).val($(this).data('oldValue'));
            }
            if (valueCurrent <= maxValue) {
                $(".btn-number[data-type='plus'][data-field='" + name + "']").removeAttr('disabled')
            } else {
                alert('Maaf, stock tidak cukup');
                $(this).val($(this).data('oldValue'));
            }


        });
        $(".input-number").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
                // Allow: Ctrl+A
                (e.keyCode == 65 && e.ctrlKey === true) ||
                // Allow: home, end, left, right
                (e.keyCode >= 35 && e.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
    </script>
@endpush

resources/views/buyer/chat.blade.php
@extends('layouts.client-layout')

@section('page', 'Chat')

@push('css')
<link rel="stylesheet" href="{{ asset('css/chat.css') }}">
@endpush

@section('content')
<div class="container-fluid page" style="padding:100px;">
  <div class="row">
    <div class="col-md-6 col-xl-6">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="input-group">
            <h4>Silahkan Pilih User</h4>
          </div>
        </div>
        <div class="card-body contacts_body">
          <ui class="contacts">
            @foreach($users as $user)
            @if($user->dari->id != Auth::user()->id)
            <li class="user" data-id="{{ $user->dari->id }}" data-name="{{ $user->dari->store->name }}">
              <div class="d-flex bd-highlight">
                <div class="img_cont">
                  @if($user->dari->avatar == null)
                  <img src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle user_img">
                  @else
                  <img src="{{ asset('assets/img/avatar/'.$user->dari->avatar) }}" class="rounded-circle user_img">
                  @endif
                </div>
                <div class="user_info">
                  <span>{{ $user->dari->store->name }}</span>
                </div>
              </div>
            </li>
            @endif
            @endforeach
          </ui>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-6 chat">
      <div class="card">
        <div class="card-header msg_head bg-transparent">
          <div class="d-flex bd-highlight">
            <div class="img_cont img-header">
              <img src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle user_img">
            </div>
            <div class="user_info" id="user_info">
              <span></span>
              <p></p>
            </div>
          </div>
        </div>
        <div class="card-body msg_card_body">
        </div>
        <div class="card-footer bg-transparent">
          <div class="input-group">
            <div class="input-group-append">
              <span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
            </div>
            <textarea name="message" class="form-control type_msg" placeholder="Type your message..."></textarea>
            <div class="input-group-append" id="send">
              <span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('script')
<script type="text/javascript">

var id;

function getMessage(id){
  $.ajax({
    url: "chat/pilih-user",
    method: "POST",
    data:{
      id: id,
    },
    success: function(result){
      console.log(result);
      $(".msg_card_body").empty();
      $(".msg_card_body").append(result['chat']);
      $("#user_info p").text(result['total']+" Pesan");
    }
  })
}

$('.user').on('click', function(){
  $('.user').removeClass('active');
  $(this).addClass('active');
  var src = $('.user .img_cont img').attr('src');

  id = $(this).data('id');
  var name = $(this).data('name');
  $("#user_info span").text(name);
  $(".img-header img").attr('src', src);

  $(".msg_card_body").scrollTop($(".msg_card_body").height()*100000);

  setInterval(function() {
    getMessage(id);
  }, 1000);

});

$('#send').on('click', function(){
  var message = $("textarea[name='message']").val();
  sendMessage(id,message);
  getMessage(id);
  $(".msg_card_body").scrollTop($(".msg_card_body").height()*100000);
});

function sendMessage(id,message)
{
  $.ajax({
    url: "chat/send-message",
    method: "POST",
    data:{
      id: id,
      message: message,
    },
    success: function(result){
      console.log(result);
      $("textarea[name='message']").val("");
    }
  })
}

</script>
@endpush

resources/views/buyer/home.blade.php
@extends('layouts.client-layout')

@section('page', 'Toko Online')

@section('content')
    <div class="row header">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row">
                        <div class="col-xs-12 col-md-5">
                            <h1>Mari bergabung dengan <span style="color:#388A6B;">Gambung</span> Store</h1>
                            <p>Kualitas produk gambungstore adalah kualitas nomor 1. Dibuat dengan detail dan memastikan
                                quality control produk, agar customer dapat menikmati kualitas maksimal dari produk
                                tersebut.</p>
                            <a href="/produk" class="btn btn-success">Beli Sekarang</a>
                        </div>
                        <div class="col-7 text-center">
                            <img src="{{ asset('assets/img/carousel/1.png') }}" alt="image" height="75%" width="45%">
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-5">

                </div>
                <div class="col-md-7">

                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row produk-landing">
        <div class="col-12 text-center">
            <h1>Produk Kami</h1>
            <hr class="divider">
        </div>
        @isset($products)
            @foreach ($products as $product)
                <div class="col-xs-12 col-md-4">
                    <div class="image-product">
                        @if (isset($product->images[0]->image_name))
                            <img src="{{ asset('assets/img/products/') . $product->images[0]->image_name }}" alt="Produk">
                        @else
                            <img src="{{ asset('assets/img/products/product-1.jpg') }}" alt="Produk">
                        @endisset
                        <h2 class="title">{{ $product->name }}</h2>
                        <h2 class="price">{{ number_format($product->price, 2) }}</h2>
                    </div>
                    <div class="overflow text-center">
                        <div class="detail">
                            <a href="/detail-produk/{{ $product->code }}" class="btn btn-outline-light">Rincian</a>
                        </div>
                    </div>
                </div>
            @endforeach
        @endisset
    </div>
@endsection